import { describe,it,expect } from 'vitest';
import { digest } from '../src/shared';
import { emptyState,syncVault,type LocalVault,type RemoteVault,type SyncState } from '../src/plugin/sync';
function fixture(localFiles:Record<string,string>, remoteFiles:Record<string,string>) {
  const local=new Map(Object.entries(localFiles)),remote=new Map(Object.entries(remoteFiles)),copies=new Map<string,string>(),trash=new Map<string,string>();
  const revision=(content:string)=>digest(content,'SHA-1');let writes=0;let failWrites=false;let failList=false;let onRead:(()=>void)|undefined;
  const l:LocalVault={paths:async()=>[...local.keys()],read:async p=>local.get(p)??null,replace:async(p,c,expected)=>{onRead?.();onRead=undefined;if((local.get(p)??null)!==expected)throw new Error('local conflict');local.set(p,c);},trash:async(p,expected)=>{if(local.get(p)!==expected)throw new Error('local conflict');trash.set(p,expected);local.delete(p);},conflict:async(p,c)=>{copies.set(p,c);}};
  const r:RemoteVault={list:async()=>{if(failList)throw new Error('offline');return Promise.all([...remote].map(async([path,content])=>({path,sha:await revision(content)})));},read:async p=>{const content=remote.get(p);if(content===undefined)throw new Error('missing');return {path:p,sha:await revision(content),content};},write:async(p,c,sha)=>{if(failWrites)throw new Error('offline');const old=remote.get(p);if((old===undefined?null:await revision(old))!==sha)throw new Error('conflict');remote.set(p,c);writes++;return{path:p,sha:await revision(c)};},remove:async(p,sha)=>{if(await revision(remote.get(p)!)!==sha)throw new Error('conflict');remote.delete(p);}};
  const state=emptyState();const run=()=>syncVault(l,r,state,async()=>{});
  return {local,remote,copies,trash,state,run,revision,get writes(){return writes;},offline(){failList=true;},failWrites(){failWrites=true;},onPull(fn:()=>void){onRead=fn;}};
}
async function baseline(f:ReturnType<typeof fixture>,p='a.md',content='base'){f.state.files[p]={sha:await f.revision(content),hash:await digest(content)};}
describe('cross-device sync state machine',()=>{
  it('uploads and downloads an initial union and is idempotent',async()=>{const f=fixture({'a.md':'a'},{'b.md':'b'});await f.run();expect([...f.local].sort()).toEqual([...f.remote].sort());await f.run();expect(f.writes).toBe(1);});
  it('does not delete remote notes from a new empty device',async()=>{const f=fixture({},{'a.md':'remote'});await f.run();expect(f.local.get('a.md')).toBe('remote');expect(f.remote.size).toBe(1);});
  it('preserves differing initial copies',async()=>{const f=fixture({'a.md':'mine'},{'a.md':'theirs'});expect((await f.run()).conflicts).toEqual(['a.md']);expect(f.local.get('a.md')).toBe('mine');expect(f.remote.get('a.md')).toBe('theirs');expect(f.copies.get('a.md')).toBe('theirs');});
  it('pushes only local edits and pulls only remote edits',async()=>{const f=fixture({'a.md':'local'},{'a.md':'base'});await baseline(f);await f.run();expect(f.remote.get('a.md')).toBe('local');f.remote.set('a.md','second device');await f.run();expect(f.local.get('a.md')).toBe('second device');});
  it('preserves concurrent edits',async()=>{const f=fixture({'a.md':'mine'},{'a.md':'theirs'});await baseline(f);await f.run();expect(f.local.get('a.md')).toBe('mine');expect(f.remote.get('a.md')).toBe('theirs');});
  it('reconciles an acknowledged-lost upload by content equality',async()=>{const f=fixture({'a.md':'same edit'},{'a.md':'same edit'});await baseline(f);expect((await f.run()).conflicts).toEqual([]);expect(f.state.files['a.md'].sha).toBe(await f.revision('same edit'));expect(f.writes).toBe(0);});
  it('propagates an explicit delete with the original revision',async()=>{const f=fixture({},{'a.md':'base'});await baseline(f);f.state.deleted=['a.md'];await f.run();expect(f.remote.size).toBe(0);expect(f.state.deleted).toEqual([]);});
  it('does not delete a remote edit after local deletion',async()=>{const f=fixture({},{'a.md':'remote edit'});await baseline(f);f.state.deleted=['a.md'];await f.run();expect(f.remote.get('a.md')).toBe('remote edit');expect(f.state.conflicts['a.md']).toContain('Deleted here');});
  it('restores missing local files without an observed delete event',async()=>{const f=fixture({},{'a.md':'base'});await baseline(f);await f.run();expect(f.local.get('a.md')).toBe('base');});
  it('moves remote deletions to local trash, but keeps unsynced edits',async()=>{const f=fixture({'a.md':'base'},{});await baseline(f);await f.run();expect(f.trash.get('a.md')).toBe('base');const g=fixture({'a.md':'new edit'},{});await baseline(g);await g.run();expect(g.local.get('a.md')).toBe('new edit');expect(g.remote.size).toBe(0);});
  it('keeps the source of a rename when the new upload fails',async()=>{const f=fixture({'renamed.md':'base'},{'a.md':'base'});await baseline(f);f.state.deleted=['a.md'];f.failWrites();await f.run();expect(f.remote.get('a.md')).toBe('base');});
  it('does not overwrite a local edit made while downloading',async()=>{const f=fixture({'a.md':'base'},{'a.md':'remote'});await baseline(f);f.onPull(()=>f.local.set('a.md','typing now'));await f.run();expect(f.local.get('a.md')).toBe('typing now');});
  it('leaves notes and baselines intact offline',async()=>{const f=fixture({'a.md':'mine'},{'a.md':'base'});await baseline(f);const before=structuredClone(f.state);f.offline();await expect(f.run()).rejects.toThrow('offline');expect(f.state).toEqual(before);expect(f.local.get('a.md')).toBe('mine');});
  it('never uploads settings, conflict copies or non-Markdown data',async()=>{const f=fixture({'.obsidian/token.md':'secret','Semantic Engine Conflicts/x.md':'remote','image.png':'binary','a.md':'note'},{});await f.run();expect([...f.remote.keys()]).toEqual(['a.md']);});
});
